### PR TITLE
Fix depwarn and error in the test on 0.6

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by giordano** [comment]
Thank you.  `SpecialFunctions` should be added `test/REQUIRE` (or I should use integrals not involving special functions).  I can do that, if you don't have the time.

**Comment by yuyichao** [comment]
......................... I did that in the local version but I think I did a `git clean` before running `git add .` ..........................

**Comment by yuyichao** [comment]
hmm. that's not what happened.. seems taht REQUIRE is ignored?...

**Comment by yuyichao** [comment]
I added `test/REQUIRE`, why is `test/` ignored?

**Comment by giordano** [comment]
> why is `test/` ignored?

Good question, I probably ignored the whole directory when I should have ignored only the generated files.  Thanks for spotting.

**Comment by giordano** [comment]
I liked the idea of having exact results, but they're not really useful, as the integrals are computed with much lower precision.  Constant literals avoids loading an external package just for the test (which makes the test annoyingly slow).  Thanks again.

**Pull request merged**
